### ISSUE TITLE
dot output label is not human friendly

### ISSUE THREAD

**Issue by wildthink** [palle-k/Covfefe#1]
I see that you are moving forward with swift 4.1 but is there any chance you could point me in the right direction to clean up the dot output as illustrated with `your parser.syntaxTree(for: "(a + b)*(-c)")` example?

```
	node29 [label="Index(_compoundOffset: 40, _cache: Swift.String.Index._Cache.utf16)..<Index(_compoundOffset: 44, _cache: Swift.String.Index._Cache.utf16)" shape=box]
```

Thanks.

**Comment by palle-k** [comment]
The syntax tree leafs store string ranges but you can map it to store strings instead using the `mapLeafs` function:

```swift
let string = "(a+b)*(-c)" 
let syntaxTree = parser.parse(string)
let humanReadable = syntaxTree.mapLeafs { leaf in
    String(string[leaf])
}
```
