### ISSUE TITLE
ABNF support

### ISSUE THREAD

**Issue by MaxDesiatov** [palle-k/Covfefe#2]
I would like to be able to parse [Dhall](https://dhall-lang.org/), which provides [an ABNF grammar](https://github.com/dhall-lang/dhall-lang/blob/a53a620df888b97fe23598356be7157bda0c8e21/standard/dhall.abnf). As far as I understand, [ABNF is more standardized](https://github.com/Engelberg/instaparse/blob/master/docs/ABNF.md), so I wonder how hard would it be for Covfefe to support it?

**Comment by palle-k** [comment]
I will look into it. From a first look at ABNF, it doesn't look too hard.

Note that the algorithms that Covfefe provides don't have amazing performance and depending on the type of grammar you're working with, LL or LR parser implementations will likely perform better.

**Comment by palle-k** [comment]
I've released a new version that has ABNF support. I have tested it with the Dhall grammar.

**Comment by MaxDesiatov** [comment]
@palle-k that's amazing, thank you!
