### ISSUE TITLE
Ambiguous Grammar

### ISSUE THREAD

**Issue by mlajtos** [palle-k/Covfefe#9]
Hello,

I am using EarleyParser with following EBNF grammar:

```ebnf
    start           = [expression];
    expression      = atom | operation;
    operation       = expression, atom, atom;
    atom            = brackets | number | symbol;
    brackets        = '(', expression, ')';
    number          = {digit};
    symbol          = letter | "+" | "-";
    letter          = 'a' ... 'z';
    digit           = '0' ... '9';
```

(Yes, no operator precedence – '1+2-3+4' should be parsed as `((1+2)-3)+4`.)

String '121' is ambiguous – sometimes parsed as number '121' and sometimes as infix operation '1 2 1' where '2' is operator and ones are operands. If I use method `allSyntaxTrees(for:)` I get both, which is okay, but method `syntaxTree(for:)` returns non-deterministicaly both trees.

Is there any way to:

1. always return the same tree for ambiguous grammar, or
2. make the grammar unambiguous, so '121' is parsed as number, or
3. do something else which I don't know?

I have an [Ohm/JS](https://ohmlang.github.io) (Packrat parser) background and there isn't such problem, so I am a bit confused right now.

**Comment by mlajtos** [comment]
The easiest way is probably to split an atom...

```ebnf
    start           = [expression];
    expression      = operation | atom;
    operation       = expression, atom2, atom;
    atom            = brackets | number | symbol;
    atom2           = brackets | symbol;
    brackets        = '(', expression, ')';
    number          = {digit};
    symbol          = letter | "+" | "-";
    letter          = 'a' ... 'z';
    digit           = '0' ... '9';
```

**Comment by palle-k** [comment]
Rules don't have precedences and Covfefe employs some hashing techniques for performance reasons, leading to potentially non-deterministic parsing results.

As you've figured out, the best solution is to make the grammar unambiguous by eliminating non-terminals which produce variable length strings where a suffix of one can be a prefix of a subsequent one.

So you should probably avoid having one number being followed by another without any kind of delimiter in between.
